package trade.wayruha.paradex.dto;

public enum CancelReason {
    USER_CANCELED, NOT_ENOUGH_MARGIN, EMPTY_MARKET, POST_ONLY_WOULD_CROSS, REMAINING_IOC_CANCEL,
    UNEXPECTED_FAILURE, DELEVERAGE, IN_LIQUIDATION, SELF_TRADE, ASSET_UNAVAILABLE, ASSET_EXPIRED,
    MARKET_NOT_OPEN, ORDER_TYPE_INVALID, PRICE_NOT_AVAILABLE, EXPIRED, EXCEEDS_MAX_SLIPPAGE,
    TIMEOUT, ORDER_EXCEEDS_POSITION_LIMIT, REDUCE_ONLY_WILL_INCREASE
}